
  MDL_COMN_DEFAULT_QUEUE_SERVICE: RMQ
  MDL_COMN_RMQ_HOST: localhost
  MDL_COMN_RMQ_USERNAME: test
  MDL_COMN_RMQ_PASSWORD: test
  MDL_COMN_RMQ_PORT : 32781

  MDL_COMN_DEID_TASKS_QUEUE : DEID_Tasks

  MDL_COMN_AWS_ACCESS_ID: id
  MDL_COMN_AWS_ACCESS_KEY: key
  MDL_COMN_DEFAULT_STORAGE_SERVICE: S3
  MDL_COMN_STORAGE_CONTAINER_NAME: bucket
  MDL_COMN_AWS_REGION_NAME : region

